### ISSUE TITLE
wiki: Not able to use specified bootloader entrance method on MacOS w/ BL654 451-00003

### ISSUE THREAD

**Issue by ejohnso49** [LairdCP/UwFlashX#1]
## Issue
When using the guide in the Wiki [Upgrading-BL654-BL654PA-Firmware](https://github.com/LairdCP/UwFlashX/wiki/Upgrading-BL654-BL654PA-Firmware), the instructions for the BL654 say to use the bootloader entrance method `FTDI reset & AT+FUP command (BL654 USB)`. This results in the following error message: `Failed. Error code -2: FTDI-based reset functionality not supported on Mac, please run on Linux/Windows`.

## Potential Workaround
I was able to update the dongle firmware by changing the bootloader entrace method to: `AT+FUP command (smartBASIC)`. It appears that everything updating successfully as the version string returned with `AT i 3` is the newest firmware v29.4.6.0 So far I do not see any issues but just wanted to flag the inconsistency in the docs. I don't know if this workaround is correct and wanted some clarification. Thanks!

*Note*: I had previously run `AT&F *` before my first attempt at upgrading the firmware.

**Comment by thedjnK** [comment]
The instructions for using FTDI reset method apply to the BL654 dongle only, not any other BL654/BL654PA-based product and is used to escape from an autorun application which is running on the module (if there is an autorun application loaded which does not use the UART then it is not possible to exit out of this application without using the FTDI reset method). I shall update the wiki to detail this, thank you.

**Comment by ejohnso49** [comment]
Ah okay great that makes sense. Just to document my case more clearly, I was using a 451-00003 w/ MacOS in this instance. Thank you for the clarification!
